version: "3.8"
services:
  temporal-postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U temporal" ]
      interval: 5s
      timeout: 3s
      retries: 20

  temporal:
    image: temporalio/auto-setup:1.27.3
    depends_on:
      temporal-postgres:
        condition: service_healthy
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgres
    ports:
      - "7233:7233"
    healthcheck:
      test: [ "CMD", "tctl", "--address", "127.0.0.1:7233", "cluster", "health" ]
      interval: 5s
      timeout: 5s
      retries: 30
  temporal-ui:
    image: temporalio/ui:2.39.0
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "8088:8080"
    depends_on:
      - temporal
volumes:
  temporal_pg_data: {}
